### ISSUE TITLE
Sound output control by System Preferences on MacOS?

### ISSUE THREAD

**Issue by JeffFessler** [JuliaAudio/PortAudio.jl#108]
The `PortAudioStream` method lets us pick a specific audio device for output, but often I would prefer to have the audio go out to whatever the user has selected under System Preferences on a Mac, instead of having to specify it at the Julia code level.
When I run `devices()` I see all the specific devices but I don't see any option to "let the system decide."  Is there a way to provide that option?

On a related note, the set of available output devices can change dynamically, e.g., when the user plugs in a HDMI cable or connects to AppleTV.  So far I have to restart Julia after making such connection changes so that `devices()` finds the new options.  Again, if audio could be routed to the user's choice under System Preferences then hopefully it could be more seamless.

Or at least if there were a "refresh the device list" option in the package?  (Maybe there is but it isn't documented yet?)

**Comment by JeffFessler** [comment]
Thanks a million - that reply was very helpful, because now I can call the following function and I have verified that it updates appropriately when I change the default in system preferences (on a Mac).  If you think this is useful I can make a PR (with docstring).  If not, at least this issue's discussion might help others too.  Feel free to close the issue if you want to leave it at this.

```julia
import PortAudio

function get_default_output_device() 
    PortAudio.terminate()
    PortAudio.initialize()
    return PortAudio.devices()[1 + PortAudio.get_default_output_index()]
end
```

**Comment by bramtayl** [comment]
Eh, I could be convinced something like `refresh_devices` with just the first two lines could be helpful. I still don't understand why you need to get the default though, because the `PortAudioStream` constructor should do that for you? https://github.com/JuliaAudio/PortAudio.jl/blob/9c701415c0a1ba1faffac5211252a95978a9e719/src/PortAudio.jl#L845

**Comment by JeffFessler** [comment]
The use case that led to this question is the following.  I am teaching a music signal processing class using this package.
I prepare a demo in my office before class and it is working fine (coming out my laptop speakers).  Then I walk into the classroom and connect to AirPlay or HDMI projector (that has audio) but unfortunately the sound still comes out of my laptop speakers instead out of the room audio - unless I restart Julia (which I don't want to do because of time-to-first plot etc.).  The refresh would do it but it's an extra step that I'd rather not take during class time.
Full disclosure, I am actually using [Sound.jl](https://github.com/JeffFessler/Sound.jl) because it has a simpler interface that is more familiar for my freshman students.  So I am going to simply build the "refresh" into that and I'll be all set.

It might be more convenient for all users if the default PortAudio constructor did a "refresh" by default, because sending the audio to the *current* system default output at the time of the stream call seems more natural than whatever audio device was the default when PortAudio was first invoked.  But if there is some downside to building that refresh here then that's fine, I'll just build it into Sound.jl.  Thanks again for the super helpful answers!

**Comment by bramtayl** [comment]
I think there might be a performance cost to restarting PortAudio, and so I'm not sure it would be good to do it by default.

**Comment by JeffFessler** [comment]
Ok, I'll close this then.  Thanks.
