### ISSUE TITLE
README issue for "by name" example

### ISSUE THREAD

**Issue by JeffFessler** [JuliaAudio/PortAudio.jl#112]
This heading in the README does not seem to match the code that uses `"default'`
https://github.com/JuliaAudio/PortAudio.jl#open-your-built-in-microphone-and-speaker-by-name

I overlooked this when we were working on #111.  No time to fix right now, so just flagging it.

**Comment by bramtayl** [comment]
Oh, the PortAudio device on my laptop is literally called "default".

**Comment by JeffFessler** [comment]
Oh, interesting!  On my mac laptop, `devices` returns:

```
3-element Vector{PortAudio.PortAudioDevice}:
 "DisplayPort" 0→2
 "MacBook Pro Microphone" 1→0
 "MacBook Pro Speakers" 0→2
```
And if I try to use the example in the readme with `"default"` I get:
`ERROR: KeyError: key "default" not found`.

Is there a way to make it more universal?

**Comment by bramtayl** [comment]
Hm, I can't think a way to make it more universal, because the names of devices depends on hardware.

**Comment by JeffFessler** [comment]
Here's an ugly way that does work, but there really should be a better way:
```julia
input = devices()[PortAudio.get_default_input_index()+1]
output = devices()[PortAudio.get_default_output_index()+1]
PortAudioStream(input, output) do stream
```
Actually, `input` is a device, not a string here, so this is not really the same.
Personally I would prefer the example to use names that are more descriptive like
```julia
PortAudioStream("Built-in Microphone", "MacBook Pro Speakers") do stream
``` 
but this is not universal, so I'll just close this issue.
We can wait to see if anyone gets confused by the `"default"` option and address it then.
