### ISSUE TITLE
Linux configuration issues

### ISSUE THREAD

**Issue by leios** [JuliaAudio/PortAudio.jl#114]
Hello, I am trying to get the PortAudio package to run on my machine; however, the tests with sound all seem to hang. I tried following the README, and all the examples at the bottom also hung. I am not sure if this is a common occurrence or if anyone knows how to solve the problem.

Context:
My OS is Arch Linux. I sometimes have a jack server running, but use PulseAudio for most things. I honestly don't know what other context is useful, so I can provide more specifics upon request.

Debug mode shows the following:
```
┌ Debug: ALSA lib pcm_dsnoop.c:600:(snd_pcm_dsnoop_open) unable to open slave
│ ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
│ ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
│ ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
│ ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
│ ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_jack.so (/home/leios/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_jack.so: cannot open shared object file: No such file or directory)
│ ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_jack.so (/home/leios/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_jack.so: cannot open shared object file: No such file or directory)
│ ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
│ ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
│ ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/home/leios/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)
│ ALSA lib dlmisc.c:339:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/home/leios/.julia/artifacts/d587f48a6815c72dec4b083bf297caec7a8e3f4b/lib/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)
│ ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
│ ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
│ ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
│ ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
└ @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:113
```

However, there is no error or warning presented when trying the following example:

```
using PortAudio, SampledSignals
S = 8192 # sampling rate (samples / second)
x = cos.(2pi*(1:2S)*440/S) # A440 tone for 2 seconds
PortAudioStream(0, 2; samplerate=S) do stream
    write(stream, x)
end
```

It just provides a 0.5 second beep and then hangs

**Comment by bramtayl** [comment]
Once it hangs, can you interrupt with control c?

**Comment by leios** [comment]
Unfortunately, not without segfaulting. I need to either input ctrl+C for about a minute or close the shell entirely. I will update with error messages tomorrow. I got a bit further but *just* shut down the computer for the evening my time.

**Comment by bramtayl** [comment]
Ok, thanks. Maybe try on master too?

**Comment by JeffFessler** [comment]
We are registering a new version right now (v1.2).  It will take an hour or so.
After that, can you please update and try again?

**Comment by leios** [comment]
I have been using master for the tests and just updated. Everything still hung, but I worked through a few of the errors present in the debug message. Namely,
1. `could not open slave` was fixed with: https://dev.to/setevoy/linux-alsa-lib-pcmdmixc1108sndpcmdmixopen-unable-to-open-slave-38on
2.  I then forced my default devices to be 0 in my `~./asoundrc` like so: ```
pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw
        card 0
}
```

This stopped the hanging issue; however, I cannot get the example script to run with a sampling rate of `S=8192`. Not setting the keyword works, but the tone is higher pitched (I think) and about 1 second.
Here is the error with `S=8192`:

```
julia> PortAudioStream(0, 2; samplerate=8*8192) do stream
           write(stream, x)
       end
Expression 'paInvalidSampleRate' failed in '/workspace/srcdir/portaudio/src/host
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->playback, outParams, 
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, s
ERROR: PortAudioException: Invalid sample rate
Stacktrace:
 [1] handle_status(error_number::Int32; warn_xruns::Bool)
   @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:102
 [2] handle_status
   @ ~/projects/PortAudio.jl/src/PortAudio.jl:93 [inlined]
 [3] PortAudioStream(input_device::PortAudio.PortAudioDevice, output_device::PorPtr{Nothing}, latency::Nothing, output_info::Ptr{Nothing}, reader::PortAudio.Sam
   @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:779
 [4] PortAudioStream(input_channels::Int64, output_channels::Int64; keywords::Ba
   @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:864
 [5] PortAudioStream(::var"#25#26", ::Int64, ::Vararg{Int64}; keywords::Base.Pai
   @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:875
 [6] top-level scope
   @ REPL[17]:1
```

The fact that I can hear output indicates that I am using the right output device, I think; however, the following example was also causing problems:

```
stream = PortAudioStream(2, 2)
try
    # cancel with Ctrl-C
    write(stream, stream)
finally
    close(stream)
end
```

This one kept outputting:

```
┌ Warning: libportaudio: Input overflowed
└ @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:99
┌ Warning: libportaudio: Output underflowed
└ @ PortAudio ~/projects/PortAudio.jl/src/PortAudio.jl:99
```
Into the REPL. Maybe the devices are actually incorrect then?

`devices()` gives me:
```
30-element Vector{PortAudio.PortAudioDevice}:
 "HD-Audio Generic: ALCS1200A Analog (hw:0,0)" 2→6
 "HD-Audio Generic: ALCS1200A Digital (hw:0,1)" 0→2
 "HD-Audio Generic: ALCS1200A Alt Analog (hw:0,2)" 2→0
 "HDA NVidia: HDMI 0 (hw:1,3)" 0→8
 "HDA NVidia: HDMI 1 (hw:1,7)" 0→8
 "HDA NVidia: HDMI 2 (hw:1,8)" 0→8
 "HDA NVidia: HDMI 3 (hw:1,9)" 0→8
 "HDA NVidia: HDMI 4 (hw:1,10)" 0→8
 "HDA NVidia: HDMI 5 (hw:1,11)" 0→8
 "HDA NVidia: HDMI 6 (hw:1,12)" 0→8
 "Scarlett Solo USB: Audio (hw:2,0)" 2→2
 "HD Pro Webcam C920: USB Audio (hw:3,0)" 2→0
 "Logitech Webcam C930e: USB Audio (hw:4,0)" 2→0
 "sysdefault" 128→128
 "front" 0→6
 "surround21" 0→128
 "surround40" 0→6
 "surround41" 0→128
 "surround50" 0→128
 "surround51" 0→6
 "surround71" 0→6
 "iec958" 0→2
 "spdif" 0→2
 "pulse" 32→32
 "a52" 0→6
 "speex" 1→1
 "upmix" 8→8
 "vdownmix" 6→6
 "dmix" 0→2
 "default" 2→6
```

But maybe I don't understand what the `2→6` notation means for my default device. I tried looking it up on the portaudio site, but it's been down all day.

As I am no longer getting hanging issues, I have renamed the issue to "Linux configuration issues." I will keep poking around, but if you have run into something like this and can point me in the right direction, that would be great!

**Comment by bramtayl** [comment]
Thanks, that's very helpful.

A lot of the ALSA warnings are ok to ignore.

2→6 means that the maximum input channels is 2 and the maximum output channels is 6. We should probably add that to the docs (or maybe come up with better notation).

The overflow and underflow warnings are ok to ignore for now.

Why did you change the default device to 0 in the ALSA config? Whichever that device is seems to not support a sample rate of 8192. The default sample rate for that device is different, which is why the pitch is shifted.

**Comment by leios** [comment]
Ok this is a bit unhelpful, but I recently changed my audio setup to pipewire from Pulse / Jack. Somehow this fixed everything. The microphone audio was delayed by roughly 3 seconds in the following example:
```
stream = PortAudioStream(2, 2)
try
    # cancel with Ctrl-C
    write(stream, stream)
finally
    close(stream)
end
```

For now, I will close the issue as it seems to be resolved. Sorry for the trouble, but thanks for the quick response! I noticed a few typos in the README. Do you mind if I add these as a PR? Maybe add a little to the docs?

**Comment by JeffFessler** [comment]
Refinements to the Readme and docs are always welcome!
