### ISSUE TITLE
Is the blocking Read/Write Functions implemented ? 

### ISSUE THREAD

**Issue by feima0011** [JuliaAudio/PortAudio.jl#18]
It seems like that the portaudio.jl only implemented the callback method,
but not the blocking Read/Write Functions like 
http://portaudio.com/docs/v19-doxydocs/blocking_read_write.html

**Comment by ssfrr** [comment]
Portaudio.jl uses the callback api to communicate to the underlying C library, but to your Julia code it always uses a read/write API with the `PortAudioStream` type, which internally has a `PortAudioSource` and `PortAudioSink` that handle `read` and `write`, respectively.

In general the idea with `PortAudio.jl` is to provide an easy-to-use API for getting audio in and out of all devices that libportaudio supports, not necessarily to expose all the low-level portaudio functionality directly. That said, if there are low-level features that you have a use-case for that aren't exposed, definitely file an issue.
