### ISSUE TITLE
Support Duplex Streams

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#2]
(conversation with @seebk continued from seebk/PortAudio.jl#3)

I think that rather than `PortAudioSink` and `PortAudioSource` there will be a `PortAudioStream` with `sink` and `source` fields, so you can open a duplex stream but then use the same read/write API defined in SampleTypes. It probably also makes sense to define the `read!`, `read`, and `write` fields on `PortAudioStream` to reference the internal `sink` and `source`. So duplex processing would look like:

```julia
stream = PortAudioStream(Float32, 48kHz, 2, 2) # two in, two out
buf = SampleBuf(Float32, 48kHz, 1024, 2)
while true
    read!(stream, buf)
    # do your processing on buf
    write(stream, buf)
end
```
Does that seem like it would work for your use case?

I've also been talking to some of the PortAudio developers and I'm planning on re-working how I interface with PortAudio again to use the callback interface. This way we can be sure we never have underruns on the PortAudio side because the callback gets run in the high-priority audio thread. We have to be pretty careful to make sure we don't do anything non-threadsafe in the callback, but I think I've got it mostly worked out. I'm planning on doing the duplex stuff described above at the same time as this refactor.

**Comment by seebk** [comment]
Yes, that looks like it does the job. At that occasion you could maybe also think about changing the order of arguments. From my point of view most important is the the channel configuration which should come first. Then followed by the sample rate, buffer size and the data type all having a default which can be overridden when necessary. But that's just my two cents.

**Comment by ssfrr** [comment]
Alrighty, in the latest master now we can open duplex streams. Also, now all stream properties besides input and output channels count are keyword arguments, so opening a single-channel input with a 1024-frame buffer is `PortAudioStream(1, 0; bufsize=2014)`, or a stereo duplex with 44.1kHz samplerate is `PortAudioStream(2, 2; samplerate=44100Hz)`.

I'm also now using PortAudio's callback API instead of blocking read/write. This means we have a small amount of code running in the audio thread, so even Julia is busy doing JIT or GC we're still able to keep the underlying Host API fed with zeros so it stays happy.
