### ISSUE TITLE
Additional options for lower latency / realtime use

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#21]
(reported by @feima0011 in #16)

> In my project, I do some real time audio signal processing.
> I determine at each time what write to the speaker, according
> to the data I received from the microphones.
> 
> PortAudio C program offers two methods for communicating audio data:
> (1) an asynchronous callback interface, where PortAudio calls a user
> defined callback function when new audio data is available or required, and
> (2) synchronous read and write functions which can be used in a blocking or
> non-blocking manner.
> 
> The Portaudio.jl provided the blocking API, but internally use the asynchronous
> callback interface provided by the C program. That cause some problems to me.
> I want to
> (1) control the time when data are received, and the time when the data are output.
> (2) the latency between the read and write process.
> (3) the blocking API provided by Portaudio C program directly.
> 
> The advantage of ASIO api over the other audio api on Windows,
> is its low latency feature.
> 
> I my project, I have to make sure that the latency of a read-and-write process is as
> small as possible.

**Comment by ssfrr** [comment]
Why would you want to use libportaudio's blocking API? Given that ASIO is callback-based, using libportaudio's blocking read/write API introduces a context switch where the callback passes data to the buffers that feed the streams you're reading and writing from, which is basically the same thing that PortAudio.jl is doing (libportaudio passes the callback through from ASIO to PortAudio.jl, which then feeds the buffers). So there shouldn't be any additional latency introduced by PortAudio.jl relative to libportaudio's blocking API. (If we could use the callback API all the way through it would be lowest-latency, but Julia code can't be called from a different thread context, so that's not an option).

PortAudio.jl also provides the `synced=true` keyword option that will give you deterministic latency.

**Comment by feima0011** [comment]
I dislike so many wrappers above the core portaudio functions. 
We are moving the development platform form computer to DSP board,
where there is no operating system and not much computational resources.

**Comment by bramtayl** [comment]
Hi @feima0011 I'm not 100% clear I understand you suggestion. The package currently uses the blocking API in it's internals, but I agree that it would be a good idea to offer users the option to access the blocking API as well, which is covered by #56. I think that would suit your needs, so I'll close for now, but feel free to reopen if I misinterpreted.
