### ISSUE TITLE
LoadError: None of the selected providers can install dependency libportaudio.

### ISSUE THREAD

**Issue by bramtayl** [JuliaAudio/PortAudio.jl#23]
I'm trying to test MusicBoxes on travis and I'm running into this error. I don't know much about BinDeps or how it works but it might be nice to figure out a way to get portaudio to work in CI.

https://travis-ci.org/bramtayl/MusicBoxes.jl/jobs/383754441

**Comment by ssfrr** [comment]
Duplicate of #1?

**Comment by bramtayl** [comment]
Oh, yup
