### ISSUE TITLE
Trying to reach computers audio before it goes to speakers..

### ISSUE THREAD

**Issue by EMCP** [JuliaAudio/PortAudio.jl#26]
I am on a Mac, have Julia working and PortAudio working.. successfully ran a microphone example..  however what I am looking to do is record the audio coming from applications on my mac.

I wonder if I need to route the audio using another piece of software like https://rogueamoeba.com/loopback/ .. in order to record what's playing on the mac .. via `PortAudio.jl`

Or do I just need to read the output properly.. below is my attempt to reading speaker output.. the code never seems to complete 20 seconds and I am forced to close it.

```
Pkg.add("PortAudio")
Pkg.add("LibSndFile")

using PortAudio, SampledSignals, LibSndFile

PortAudio.devices()

stream = PortAudioStream("Built-in Output", 0, 2)

print("Starting...20seconds")
buf = read(stream, 20s)
print("Buffer closed") . // never reaches here
save(joinpath(pwd(), "Data", "output.ogg" ), buf)

```

**Comment by ssfrr** [comment]
You'll need a separate piece of software to create a virtual loopback device if you want to record the output of programs. I've often used SoundFlower in the past, but i'm not sure if it's still being maintained. JACK is also an option. It allows very powerful routing but can be tricky to get up and running.

**Comment by EMCP** [comment]
I got it working with Jack2 on OS X.. The application in question is Ableton Live and I start the Jack Server .. and after a couple runs of Julia, PortAudio sees the device as a target to read!

<img width="581" alt="screen shot 2018-08-07 at 9 35 46 pm" src="https://user-images.githubusercontent.com/3691722/43798122-e37f9b66-9a89-11e8-97d9-eea40ce86028.png">


```
stream = PortAudioStream("JackRouter", 2, 2)

print("Starting...20seconds")
buf = read(stream, 20s)
print("Buffer closed")
```

Now i just need to create a version that keeps reading data non-stop

**Comment by ssfrr** [comment]
Great! At one point we had a native [JACK Julia package](https://github.com/JuliaAudio/JACKAudio.jl), but I haven't had time to maintain it (PortAudio is useful to a lot more folks). If you ever get the itch and want to take a crack at updating it let me know and I can give some guidance.

**Comment by EMCP** [comment]
Looks like I can test the JackClient can successfully instantiate itself and smooth out the wiring of Live and System?  Will add it into the project and see how it goes.  First priority is to create an audio stream that continuously reads Ableton Live and gives me the chance to process what's coming out.  I bet the Jack Client will come in handy if I need to route to a 2nd computer
