### ISSUE TITLE
Error Using v1.0.0 Julia and Port Audio on RPi3

### ISSUE THREAD

**Issue by EMCP** [JuliaAudio/PortAudio.jl#33]
I know I have a separate issue for `v0.6.0`, thought it might be better to create a ticket for what I am seeing using the latest binary for ARM v7 Julia `v1.0.0` 

Thankfully I got the binary working after a weekend of failed compilations.. and just discovered I need to set `JULIA_HOME` .. guessing this is a path to the install of the binary?

```
Import Pkg
Pkg.add("PortAudio")
```

result 

```
┌ Error: Error building `PortAudio`: 
│ ERROR: LoadError: UndefVarError: JULIA_HOME not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /home/pi/.julia/packages/PortAudio/LfjGt/deps/build.jl:5
└ @ Pkg.Operations /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

```

I could update the docs or maybe users know enough to deal with this without explicit explanation.. can PR if needed

in `.bashrc`
```
export JULIA_HOME=/path/to/julia-v1.0.0`
```
then do
```
julia
```
once inside Julia
```
import Pkg
Pkg.build("PortAudio")
```

but I still get 

```
julia> Pkg.build("PortAudio")
...
  Building WinRPM ──────────→ `~/.julia/packages/WinRPM/rDDZz/deps/build.log`
  Building PortAudio ───────→ `~/.julia/packages/PortAudio/LfjGt/deps/build.log`
┌ Error: Error building `PortAudio`: 
│ ERROR: LoadError: UndefVarError: JULIA_HOME not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /home/pi/.julia/packages/PortAudio/LfjGt/deps/build.jl:5
└ @ Pkg.Operations /buildworker/worker/package_linuxarmv7l/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

julia> exit
exit (generic function with 2 methods)

julia> quit()
ERROR: UndefVarError: quit not defined
Stacktrace:
 [1] top-level scope at none:0

```

**Comment by EMCP** [comment]
ahh this is solved by setting

```
export JULIA_HOME=/path/to/julia-v1.0.0/bin
```

**Comment by EMCP** [comment]
After reading https://docs.julialang.org/en/v0.6.0/manual/environment-variables/

it seems `PortAudio`'s build does not pick up the already set environment variable within Raspbian .. leaving me to do this within Julia

```
julia> ENV["JULIA_HOME"]="/path/to/julia-v1.0.0/bin"
```

**Comment by ssfrr** [comment]
PortAudio doesn't yet have a release for Julia 1.0. That will fix this issue. I've got a branch that seems to be working, but got bogged down in a libuv bug that took some time to track down. Now that I've got a handle on the libuv bug I should be able to get a workaround going, hopefully sometime this week.
