### ISSUE TITLE
Not supporting Julia 1.0 

### ISSUE THREAD

**Issue by Chetank99** [JuliaAudio/PortAudio.jl#34]
Unsatisfiable requirements detected for package PortAudio [80ea8bcb]:
PortAudio [80ea8bcb] log:
├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 1.0.0] or uninstalled
├─restricted to versions * by an explicit requirement, leaving only versions [0.2.1, 0.3.0, 0.4.0, 0.5.0, 1.0.0]
└─restricted by julia compatibility requirements to versions: uninstalled — no versions left
*unable to install

**Comment by mriede** [comment]
I have this problem as well, using Julia 1.0.1

**Comment by Thib03** [comment]
Is there a solution on Windows ?

**Comment by ssfrr** [comment]
Did you try the `julia1` branch? I need to do some more cleanup work, but things should still be more-or-less functional. You may need to checkout `RingBuffers`, `SampledSignals` at `master` as well.

**Comment by JMurph2015** [comment]
@ssfrr 1) you're doing great work, one of my favorite personal projects is a hard-depend on PortAudio.jl and I haven't been able to migrate it because of the incompatibility 2) are there any updates on whether everything is back to normal / when this can be merged?

**Comment by ssfrr** [comment]
Unfortunately I'm a bit over-subscribed at the moment and haven't had much time for work that isn't a dependency for my research. The `julia1` branch is partway through switching to a `BinaryBuilder` setup, which should fix a few issues and annoyances, but probably what I should do is separate out that work from the bare minimum to be 1.0 compatible. Unfortunately there are some complexities to keep RingBuffers.jl and PortAudio.jl in sync and I haven't had time to work through the issues for a stable release.

PRs welcome. :wink:

**Comment by jpsamaroo** [comment]
@ssfrr do you have a link to your work on a PortAudio BB repo? I'd be happy to spend some time getting things working, since currently things don't work for me on the julia1 branch (probably because of how my distro ships the library).

**Comment by ssfrr** [comment]
That would be stellar. I just realized I haven’t pushed that repo to github. I’ll do that when I get to my computer and let you know. Thanks for the offer!

**Comment by ssfrr** [comment]
OK, I just pushed the current work [here](https://github.com/ssfrr/PortAudioBuilder). There's also a builder for RingBuffers.jl [here](https://github.com/JuliaAudio/RingBuffersBuilder). I think that one works. It's been about a year since I've worked on this, and I think in the mean time there have been some changes to the PortAudio build system that might make it a little easier.

**Comment by kskyten** [comment]
There's now a [binary package](https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl) for libportaudio. Other than switching to use that, what needs to be done for Julia 1.3 support?

**Comment by ssfrr** [comment]
That’s the main thing. I still have some work to do on that binary package before it’s ready for prime time, but we’re getting close.

**Comment by bramtayl** [comment]
Supports Julia 1.0 now!
