### ISSUE TITLE
some strange buffer issues

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#35]
I'm seeing some strange behavior where it sounds like chunks are being played out of order, or skipped, or something. Not sure if this is related to a recent change in my code or what. Possibly (but not likely) due to Julia changes somewhere around 1.1, as I haven't been using this much lately.
Currently on `master` of RingBuffers and the `julia1` branch of PortAudio
MWE:

```julia
freq = range(0.05, 0.5, length=48000)
phase = cumsum(freq)
sig = cos.(phase)
PortAudioStream(; blocksize=4096*8) do io
    write(io, sig * 0.05)
    write(io, sig * 0.05)
    write(io, sig * 0.05)
    write(io, sig * 0.05)
    write(io, sig * 0.05)
    write(io, sig * 0.05)
end
```

**Comment by bramtayl** [comment]
Hmm, well, blocksize doesn't seem to exist anymore, but I set CHUNKFRAMES to `4096*8` and this sounds fine, so closing for now
