### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by felipeacsi** [JuliaAudio/PortAudio.jl#44]
Hello, thanks for this package (and for the others too!).

I tried the "Record 10 seconds of audio and save to an ogg file" example and it seems to be missing `using FileIO` or something like that so `save` is defined. Otherwise I got `ERROR: UndefVarError: save not defined`.

Also it seems the last section about the shim library is outdated? I saw that was in the master branch but not anymore. Maybe you are aware of this but I'd rather say it.

**Comment by ssfrr** [comment]
Thanks for the heads up! Yeah, I think there are a few things that need updating with the latest changes. I'll do a pass through the README before I push a release.

**Comment by felipeacsi** [comment]
Ok, great.

**Comment by bramtayl** [comment]
Closed by https://github.com/JuliaAudio/PortAudio.jl/commit/d6c3595f03cfdb00bf0c451f7d93a64982d7d9e0 now we've got real docs!
