### ISSUE TITLE
Needs windows testing

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#45]
I haven't had time to test the latest JLL-based version (now on `master`) on Windows yet, which I definitely want to do before I release. (Unless someone else gets a chance to try it out and can report back here) :wink:

**Comment by wherrera10** [comment]
The JLL based version does compile and run under Windows. I used Windows to update the examples/lilyplay.jl file (and replaced the prior pull, which never worked under OSX), and the current version will play harmony with acceptable sync between spawned processes under Windows.

**Comment by bramtayl** [comment]
Hmm, it seems to me that @wherrera10 's trial would have solved the original issue here. Undoubtedly, the current version also needs more thorough testing on windows, but that seems like an issue that should be subsumed under #1 . I'll close for now, but feel free to reopen for specific issues on Windows.
