### ISSUE TITLE
MIDI support?

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaAudio/PortAudio.jl#50]
Sorry for the triple issue file! I don't see any reference to MIDI, so just wondering if it's in the scope of either PortAudio.jl or JACKAudio.jl, or if there's another package that's recommended for dealing with midi.

Thanks!
Oliver

**Comment by ssfrr** [comment]
No need to apologize - I'm happy for community engagement (despite not being a very conscientious maintainer lately).

The underlying `libportaudio` doesn't do anything MIDI-related, it's purely for audio.

AFAIK there aren't any Julia packages that can interface with system MIDI devices. There are some C and C++ libraries (RtMIDI, PortMIDI) that could be wrapped, but I haven't looked into them really.

There's also [MIDI.jl](https://github.com/JuliaMusic/MIDI.jl), which has had [some discussion](https://github.com/JuliaMusic/MIDI.jl/issues/32) of adding device support, but seems like it needs someone to take a crack at it.

It also looks like @jheinen has been [working on some kind of MIDI player](https://github.com/JuliaMusic/Mplay.jl) that has its own `C` library to interface with system midi devices.
