### ISSUE TITLE
Cant add PortAudio?

### ISSUE THREAD

**Issue by cormullion** [JuliaAudio/PortAudio.jl#51]
I don't know why I can't add this package:

```

(@v1.4) pkg> add PortAudio   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * PortAudio (not found in project, manifest or registry)

```

**Comment by ssfrr** [comment]
PortAudio is not registered in General - you can try the `master` branch which mostly works but there are still some issues blocking a release (mainly #42 and #46, #49 would be a nice-to-have).
