### ISSUE TITLE
PortAudio not found in registry for Julia 1.4.1

### ISSUE THREAD

**Issue by kzapfe** [JuliaAudio/PortAudio.jl#52]
Hello team:
 It is not PortAudio avaible in the repositories for julia 1.4.1?
I get the message:
```

(@v1.4) pkg> add PortAudio
ERROR: The following package names could not be resolved:
 * PortAudio (not found in project, manifest or registry)

```
, even after updating registry.

**Comment by ssfrr** [comment]
PortAudio is currently not in the registry - feel free to check out the `master` branch, which is compatible with the latest Julia, though there are still some issues before it's ready for release.
