### ISSUE TITLE
Register package?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaAudio/PortAudio.jl#54]
Any reason it isn't registered? Waiting for version 1.0? That's not usually done...

So far I only tried to install (also in 1.5) and do:

```
(@v1.7) pkg> add https://github.com/JuliaAudio/PortAudio.jl

julia> @time @time using PortAudio
  2.997193 seconds (3.08 M allocations: 194.936 MiB, 5.83% gc time, 0.25% compilation time)
  3.079666 seconds (3.14 M allocations: 198.743 MiB, 5.67% gc time, 0.24% compilation time)

julia> @time @time using PortAudio
  1.079439 seconds (667.89 k allocations: 37.415 MiB, 1.93% gc time, 99.99% compilation time)
  1.079529 seconds (667.94 k allocations: 37.419 MiB, 1.93% gc time, 99.98% compilation time)

julia> @time using PortAudio
  0.000127 seconds (81 allocations: 6.062 KiB)
```

**Comment by KronosTheLate** [comment]
Yhea I just tried to install this package, and was wondering why it is not registered. Would lije it te be though

**Comment by PallHaraldsson** [comment]
I'm not sure about the differences with PortAudio.jl and PulseAudio.jl, if the latter should be preferred (while it's older and not maintained), but I do see:

https://github.com/JuliaPackaging/Yggdrasil/pull/2469

**Comment by bramtayl** [comment]
My reading of https://github.com/JuliaAudio/PortAudio.jl/issues/51 is that playing nicely with PulseAudio is at least one blocker. I've been trying to get a binarybuilder version of PulseAudio finished for months!

**Comment by PallHaraldsson** [comment]
I would like this one or just any package registered that work for audio on Linux, and preferally cross platform. That said, FYI (for Linux only), PipeWire may be a new thing on Linux for audio:

"It provides a low-latency, graph based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both pulseaudio and JACK."

I'm very new to this, and not sure what's preferred (on Linux).

**Comment by PallHaraldsson** [comment]
About my Pipewire comment, while it will be the default in Fedora Linux:
https://fedoraproject.org/wiki/Changes/DefaultPipeWire

>This means that all existing clients using the PulseAudio client library will continue to work as before, as well as applications shipped as Flatpak.

https://www.phoronix.com/scan.php?page=news_item&px=Fedora-34-PipeWire-Attempt

So seemingly we need to concentrate on PulseAudio (rather than Pipewire or PorAudio?).

**Comment by bramtayl** [comment]
Well, if you are any good at building software, I'm stuck on JuliaPackaging/Yggdrasil#2469

**Comment by ssfrr** [comment]
Yes, as @bramtayl mentioned, if built correctly, PortAudio can talk to PulseAudio. It can also use other audio APIs on linux as well (ALSA, JACK, maybe others) and also works on Windows and MacOS.

Perfect shouldn't be the enemy of the good here though, and it's probably better to register the package with more limited support than just keep waiting endlessly. The two main blockers for me have been

1. I've come to dislike the way I designed this and LibSndFile.jl to live on top of SampledSignals.jl - in retrospect I think it would be better for these to be low-level packages with few dependencies that use julia-native types. Then they could be used without buying into the whole SampledSignals design. I've been hesitant to do a release just to then dramatically change the API.
2. I've had very limited time in the past year or so work on Julia development so this whole collection of packages has gone somewhat falllow. If any contributors want to take on maintainer status merge PRs, do releases, etc. I would be very open to that. Given that I'm not expecting to do this refactor any time soon, I would be happy if someone wanted to register it.

**Comment by bramtayl** [comment]
I'm happy to help maintain! I could even give refactoring a stab (but more details might help). It's not what I _should_ be spending my time on, but clearly that hasn't stopped me. Caveats: I'm a hobbyist, and I don't think I could make promises about reliability.

**Comment by DenisLaboureyras** [comment]
Hello, I would be happy as well to help maintain this package, as well as the other JuliaAudio packages. Unfortunately I don't have much experience in Julia :( (only 2 months) but have a lot of free time these days and working on an audio project which uses many of these packages.
Btw, I agree with @ssfrr that this library shouldn't depend on SampledSignals.jl. For example on my project, SampledSignals had a lot of compat dependencies and was downgrading a lot of other libraries because of that, so I had to fork it. It was kind of a bummer.

**Comment by rob-luke** [comment]
> If any contributors want to take on maintainer status merge PRs, do releases, etc. I would be very open to that.

I've been a long term Julia user/developer and contributed to some of the early DSP.jl code back in my PhD. My focus changed in the last few years and I worked on the MNE python package. However, I am about to start another postdoc and plan to heavily use this package. I would be happy to support you in maintaining this package. If you wish I will be more active in reviewing PRs and provide my opinions in issues.

> Then they could be used without buying into the whole SampledSignals design.

It seems I'm against the grain here, but I love the sampledsignal design and ecosystem. I've built all my tooling on top of it.

**Comment by bramtayl** [comment]
I've been reading through the code. I have a rewrite that I could put up, but its mostly petty stylistic changes. In terms of substantive changes though

1) There's an interesting comment about a transaction based API in the code, which sounds convincing but I can't wrap my head around it. The PortAudio docs seem to suggest using a "call-back" function to interact with the buffers, which could be more convenient.
2) It seems like there's a lot of unnecessary copying. Every read and write cycle copies the contents of one buffer to another transposed buffer. Why not just give users access to a transposed view?
3) It's not clear to me that transposing is even necessary?

**Comment by rob-luke** [comment]
Perhaps it's best to keep this discussion on topic of registering package as that's the key goal. And open other issues for your other questions?

My experience has shown that mixing too many topics in one issue just results in things getting lost.

**Comment by rob-luke** [comment]
On the topic of registering the package I would propose the following rough plan.

1. Register as is before making any changes so that existing users are not locked in to any new modifications.
2. Update the CI code for greatest coverage on different platforms and versions (if required)
3. Update dependencies and Julia versions
4. Bump registered version once everything green
5. Then open up to new PRs

**Comment by ssfrr** [comment]
@bramtayl I just invited you as an admin for JuliaAudio. Go forth and register. :)

I have lots of opinions on the callback approach for PortAudio - but as @rob-luke mentioned it's probably best to take that elsewhere. LMK if you have questions or need feedback.

**Comment by rob-luke** [comment]
Thanks @ssfrr, thanks for all these amazing packages. I hope I can relieve some of the administration burden on you. And will be sure to ping you on the more interesting issues and PRs still.

@bramtayl are you happy with the plan above (https://github.com/JuliaAudio/PortAudio.jl/issues/54#issuecomment-826390099)?

If so, I will leave you to complete steps zero and one to register the package. Or let me know if you would prefer me to do this, I have done it for several packages before.

I will open a PR for step two, and update the CIs to use github actions. I have most of this code easily accessible as I just did this for auditorystimuli.jl

I have also found the following small behaviours to help efficiently run a small public repo, these may not work for us here, but I will try to follow these rough guidelines until we work out a nice flow:
* Open all PRs from personal account, not from the organisation account. This helps to keep branches clean.
* Keep PRs to single topic to make it easier to review
* For basic/simple PRs (typos, CI fixes) its ok to merge your own PR
* For anything else (CI changes, code changes, etc) ping another admin to ask for review and merge.
* For complex PRs from contributors try and get one admin to approve and the second admin to merge.

This may not work for us, but I have watched these steps simplify life in other repos.

**Comment by ssfrr** [comment]
@bramtayl I couldn't find the issue you mentioned - can you link?

**Comment by bramtayl** [comment]
Oops forgot I had closed it: https://github.com/JuliaAudio/PortAudio.jl/issues/56

**Comment by rob-luke** [comment]
I see a new version was tagged. I will test that I can install it from the registry and listen to audio with it on a fresh lab pc today. If so, I guess we can close this!!!

**Comment by rob-luke** [comment]
Looks good to me 🥳

**Comment by ssfrr** [comment]
Great work - Thanks @bramtayl and @rob-luke for all the work on getting things up to snuff.
