### ISSUE TITLE
Remove circular type definition

### ISSUE THREAD

**Issue by bramtayl** [JuliaAudio/PortAudio.jl#57]
The circular type definition for `PortAudioStream` and `PortAudioSource`/`Sink` is clever but less inferable and not strictly necessary:

Instead, we could have a nested structure:

- `Portal` (or some other name) would would contain a `PortAudioDevice`, buffer, and number of channels
- `PortAudioStream` would contain input and output portals and the pointer to the stream
- `PortAudioSource`/`Sink` would be trivial wrappers over `PortAudioStream` to show what context to use the stream in

**Comment by rob-luke** [comment]
What would be the benefit of such a change? Cleaner code? If so, could you provide a pseudo code of how a user would use this package before and after this change? As I'm not sure I completely understand your proposal and an example may help.

**Comment by bramtayl** [comment]
Ok, sorry I wasn't clear in the prompt. The issue is in the existing type definition for `PortAudioStream`:

```
mutable struct PortAudioStream{T}
    ...
    sink # untyped because of circular type definition
    source # untyped because of circular type definition
    ....
```

The untyped fields could potentially reduce performance, unless careful type assertions are used (which is a pain).

I don't think the circular type definitions are necessary: I would propose a data structure somewhat like this:

```
struct Portal{Sample}
    device::PortAudioDevice
    number_of_channels::Int
    chunk_buffer::Array{Sample,2}
end

# mutable so we can change the stream pointer to C_NULL when the stream closes
mutable struct PortAudioStream{Sample}
    input_portal::Portal{Sample}
    output_portal::Portal{Sample}
    stream_pointer::PaStream
    the_sample_rate::Float64
    latency::Float64
end

struct PortAudioSink{Sample}
    stream::PortAudioStream{Sample}
end

struct PortAudioSource{Sample}
    stream::PortAudioStream{Sample}
end
```

I think if we were careful we could make a change like this without affecting the user-interface much if at all.

**Comment by rob-luke** [comment]
Thanks for clarifying.

If you can demonstrate improved performance without modifying the user facing API that sounds fantastic. I'd be happy to test your changes locally too if you can provide a way I could benchmark the performance increase. As I think it's hard to demonstrate performance changes on the CI.

However, stylistic changes that don't provide measurable benefits or improved user experience could be avoided. This is just opinion, but i think it's respectful to try and maintain the style of original authors as it's their repo/history.

**Comment by bramtayl** [comment]
Hmm, well I doubt that it would have any noticeable performance impacts. I don't see the fields being accessed in inner loops, and even they were, type assertions would fix it. As for the original authors though, this comment https://github.com/JuliaAudio/PortAudio.jl/issues/54#issuecomment-809850052 made me think they would be ok with changing things up.

**Comment by rob-luke** [comment]
I am sure everyone is open to improvements (performance, readability, api, etc), but changes for the sake of changes may not be the best use of reviewers (other peoples) resources. Even stylistic changes require careful consideration/review.  Just my 2c. Looking again, your proposal seems more readable, so that's a benefit (although subjective).
