### ISSUE TITLE
Use clang to generate C bindings

### ISSUE THREAD

**Issue by bramtayl** [JuliaAudio/PortAudio.jl#63]
Fortunately @Gnimuc has already done the work for us here: https://github.com/Gnimuc/PortAudio.jl/tree/callback

The code is pretty much identical to what is already in libportaudio.jl, but covers the whole package. I think we could integrate it in pretty seamlessly, with some error handling padding etc.

**Comment by rob-luke** [comment]
Perhaps best to ask if the author wishes to open a PR? If they have done most of the heavy lifting already they may wish to get the credit 😃. And it would be good to encourage more community engagement.

**Comment by bramtayl** [comment]
Closed by https://github.com/JuliaAudio/PortAudio.jl/commit/d6c3595f03cfdb00bf0c451f7d93a64982d7d9e0
