### ISSUE TITLE
Pkg.build("Portaudio") install not working on Arch

### ISSUE THREAD

**Issue by ssfrr** [JuliaAudio/PortAudio.jl#8]
Something seems to be funky about the way BinDeps is installing portaudio on ArchLinux.

```
LoadError: failed process: Process(`sudo pacman -S --needed portaudio`, ProcessExited(1)) [1]
while loading /home/sfr-dev/.julia/v0.6/PortAudio/deps/build.jl, in expression starting on line 26
```

Running the same command from the terminal works fine, though it does ask for confirmation, so maybe that's tripping BinDeps up.

**Comment by bramtayl** [comment]
We use BinaryBuilder now so I'm not sure this is relevant anymore, correct me if I'm wrong
