### ISSUE TITLE
HZ not defined

### ISSUE THREAD

**Issue by tj10ai** [JuliaAudio/PortAudio.jl#86]
This is my first post of an issue; please let me know protocol: 

PortAudioStream(inchans=2, outchans=2; eltype=Float32, samplerate=48000Hz, latency=0.1, synced=false)

returns error 'HZ not defined', as seen in attachment.

![image](https://user-images.githubusercontent.com/44120150/131431536-2228f068-b86b-45a6-b6f3-6350047a1bb9.png)

**Comment by rob-luke** [comment]
Thanks for posting this issue! I confirm this is a documentation error. 

Does either of the following work?

```Julia
using PortAudio, Unitful

PortAudioStream(your_other_values, samplerate=48000u"Hz")
# or
PortAudioStream(your_other_values, samplerate=48000)
```

**Comment by tj10ai** [comment]
Robert thanks for looking into this error; I tried but both suggestions failed:

**Comment by bramtayl** [comment]
`Hz` is in `Unitful`. Try `using Unitful: Hz`

**Comment by bramtayl** [comment]
Closed by https://github.com/JuliaAudio/PortAudio.jl/pull/111
