### ISSUE TITLE
`messanger` is actually spelled `messenger`, is this on purpose?

### ISSUE THREAD

**Issue by anandijain** [JuliaAudio/PortAudio.jl#90]
its probably not worth a breaking change but this misspelling is used all throughout the codebase

does this have a special meaning or is it actually just spelled wrong?

**Comment by rob-luke** [comment]
Likely a typo, @bramtayl can you confirm?

@anandijain, if @bramtayl confirms this is a typo, could you open a PR to fix this?

**Comment by anandijain** [comment]
yeah for sure, but it would require a breaking release so i can make the PR. so it might be best to wait to merge until a few other important things get merged. (for example, i expect my libportaudio_jll pr https://github.com/JuliaPackaging/Yggdrasil/pull/3646 to be merged soon, so we can also update the compat). 

i just started using this repo to try to make a rudimentary synthesizer using https://github.com/anandijain/RtMIDI.jl

that is why i've annoyingly spammed.4 issues in the span of a day. (apologies)

thanks a bunch

**Comment by rob-luke** [comment]
> that is why i've annoyingly spammed.4 issues in the span of a day. (apologies)

Not annoying at all. Its actually motivating when you know someone is using the code.  Keep us posted on your progress, the synth looks cool

**Comment by bramtayl** [comment]
I agree with Rob, always makes me happy to hear someone using the code. Yes, this was a my mistake. A little embarrassing, but also a little funny I haven't noticed till now.

**Comment by bramtayl** [comment]
Closed by #98

**Comment by JeffFessler** [comment]
See also #115
