### ISSUE TITLE
Update to 19.7.0

### ISSUE THREAD

**Issue by nantonel** [JuliaAudio/PortAudio.jl#91]
I cannot record audio in BigSur and traced back the problem to [this issue](https://github.com/PortAudio/portaudio/issues/395).

It seems to be fixed now in v19.7.0 of PortAudio [PortAudio](https://github.com/PortAudio/portaudio).

However, I've checked the binary builder repo [libportaudio_jll.jl](https://github.com/JuliaBinaryWrappers/libportaudio_jll.jl) and it is still at 19.6.0+2. I'm not familiar with the BinaryBuilder and not sure what actually runs the updates of these packages. Perhaps some of you know better the way to fix this? Thank you!

**Comment by abhayap** [comment]
We can close this as this PR was merged: https://github.com/JuliaPackaging/Yggdrasil/pull/4158

**Comment by bramtayl** [comment]
Yay!
